{
 "title": "AiSEG2 - Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "総消費電力(W)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"総消費電力(W)\")\n  |> group(columns: [\"summary\"])\n",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '総消費電力(W)' "
    }
   ]
  },
  {
   "title": "総発電電力(W)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"総発電電力(W)\")\n  |> group(columns: [\"summary\"])\n",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '総発電電力(W)' "
    }
   ]
  },
  {
   "title": "売買電力",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"売買電力(W)\")\n  |> group(columns: [\"summary\"])\n",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '売買電力(W)' "
    }
   ]
  },
  {
   "title": "使用量ランキング",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"power\")\n  |> filter(fn: (r) => r[\"detail-type\"] == \"consumption\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> group(columns: [\"detail-section\"])\n  |> last(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 5)\n  |> keep(columns: [\"_value\", \"detail-section\"])\n",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '売買電力(W)' "
    }
   ]
  },
  { "title": "Temperature and Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "温度（リビング）",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"detail-type\"] == \"temperature\")\n  |> last()",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '売買電力(W)' "
    }
   ]
  },
  {
   "title": "湿度（リビング）",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"climate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"detail-type\"] == \"humidity\")\n  |> last()",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '売買電力(W)' "
    }
   ]
  },
  {
   "title": "エアコン合計(W)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"リビングエアコン(W)\")\n\n",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"summary\" = '総発電電力(W)' "
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"洋室２エアコン(W)\")\n\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"主寝室エアコン(W)\")\n"
    }
   ]
  },
  {
   "title": "温湿度（リビング）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"climate\")\n    |> filter(fn: (r) => r[\"detail-type\"] == \"temperature\")\n    |> group(columns: [\"detail-section\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "rawSql": "SELECT \"time\", \"value\", \"detail-section\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"detail-type\" = 'generation'"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"climate\")\n    |> filter(fn: (r) => r[\"detail-type\"] == \"humidity\")\n    |> group(columns: [\"detail-section\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  { "title": "Power - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "総消費電力(W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"総消費電力(W)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"summary\" = '総消費電力(W)' AND value IS NOT NULL) "
    }
   ]
  },
  {
   "title": "総発電電力(W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"総発電電力(W)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"summary\" = '総発電電力(W)' AND value IS NOT NULL) "
    }
   ]
  },
  {
   "title": "売買電力(W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"summary\"] == \"売買電力(W)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "rawSql": "SELECT \"time\", \"value\", \"summary\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (\"summary\" = '売買電力(W)' AND value IS NOT NULL) "
    }
   ]
  },
  {
   "title": "発電内訳",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"power\")\n    |> filter(fn: (r) => r[\"detail-type\"] == \"generation\")\n    |> group(columns: [\"detail-section\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "rawSql": "SELECT \"time\", \"value\", \"detail-section\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"detail-type\" = 'generation'"
    }
   ]
  },
  {
   "title": "利用内訳",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"power\")\n    |> filter(fn: (r) => r[\"detail-type\"] == \"consumption\")\n    |> group(columns: [\"detail-section\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "rawSql": "SELECT \"time\", \"value\", \"detail-section\" FROM \"power\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"detail-type\" = 'generation'"
    }
   ]
  }
 ]
}