name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
